services: 
  strapi:
    build:
      context: ./backend
    container_name: strapi
    ports:
      - "1337:1337"
    volumes:
      - ./backend:/srv/app
    working_dir: /srv/app
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi123
      NODE_ENV: development
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    container_name: postgres
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi123
      POSTGRES_DB: strapi
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    container_name: nextjs
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: "yarn dev"
    depends_on:
      - strapi

volumes:
  pgdata:
